// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistences.Models;

public partial class AddrExtrInfo
{
    public string Div { get; set; }

    public string Area1Code { get; set; }

    public string Area2Code { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateOnly? FileRegistDate { get; set; }

    public bool IfsuccessYn { get; set; }

    public DateOnly? Ifdate { get; set; }

    public string ExtractType { get; set; }

    public string ReflectionClsName { get; set; }

    public int? AddressIndex { get; set; }

    public virtual AdmCode AdmCode { get; set; }

    public virtual ICollection<ExtractAddress> ExtractAddresses { get; set; } = new List<ExtractAddress>();
}