// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistences.Models;

public partial class AdmCode
{
    public string Area1Code { get; set; }

    public string Area1Name { get; set; }

    public string Area2Code { get; set; }

    public string Area2Name { get; set; }

    public DateOnly CreateDate { get; set; }

    public virtual ICollection<AddrExtrInfo> AddrExtrInfos { get; set; } = new List<AddrExtrInfo>();
}