// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistences.Models;

public partial class CommonCode
{
    public string CodeGroup { get; set; }

    public string Code { get; set; }

    public string CodeName { get; set; }

    public bool? UseYn { get; set; }
}