// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistences.Models;

public partial class Complaint
{
    public int Idx { get; set; }

    public string Div { get; set; }

    public string AddressText { get; set; }

    public string UserInfo { get; set; }

    public string UserType { get; set; }

    public string ComplaintType { get; set; }

    public string Description { get; set; }

    public DateOnly CreateDate { get; set; }

    public virtual Location Location { get; set; }
}