// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistences.Models;

public partial class ExtractAddress
{
    public string Div { get; set; }

    public string AddressText { get; set; }

    public DateOnly CreateDate { get; set; }

    public string Area1Code { get; set; }

    public string Area2Code { get; set; }

    public virtual AddrExtrInfo AddrExtrInfo { get; set; }
}